In [ ]:
# NUmpy
#NUm - Numerical
#Py - Python

In [1]:
l =[1,2,3,4,5]
for i in l:
  print(i**2)

1
4
9
16
25


In [ ]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
np.len
np.square

np.len

AttributeError: module 'numpy' has no attribute 'len'

In [7]:
log(10)

NameError: name 'log' is not defined

In [1]:
import math
math.log(10)

2.302585092994046

In [2]:
import math as m #alias name
m.log(10)

2.302585092994046

In [3]:
import numpy as np

In [4]:
a = [1,2,3,4,5]

In [5]:
int(9.8)

9

In [6]:
b = np.array(a)#type casting

In [7]:
type(a),type(b)

(list, numpy.ndarray)

In [8]:
#numpy.ndarray - n dimensional array

In [9]:
l =[1,2,3,4,5]
[i**2 for i in l]

[1, 4, 9, 16, 25]

In [10]:
arr = np.array(l)
arr**2

array([ 1,  4,  9, 16, 25])

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr+2

array([3, 4, 5, 6, 7])

In [13]:
l = range(1000000)

In [14]:
%timeit [i**2 for i in l]

167 ms ± 1.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
l2 = np.array(l)

In [16]:
%timeit l2**2

674 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.ndim

1

In [15]:
n = [[1,2,3],[4,5,6]]
arr2 = np.array(n)

In [16]:
n[1][1]

5

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2.ndim

2

In [17]:
n = [[[[[[[1,2,3]]]]]],[[[[[[4,5,6]]]]]]]
arr3 = np.array(n)

In [ ]:
arr3

array([[[[[[[1, 2, 3]]]]]],





       [[[[[[4, 5, 6]]]]]]])

In [ ]:
arr3.ndim

7

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.shape #when it is 1d it will tell you number of elements in tit

(5,)

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.shape

(2, 3)

In [18]:
arr4 = np.array([[1, 2, 3,4], [4, 5, 6,4], [10, 11, 12,4]])
print(arr4)

[[ 1  2  3  4]
 [ 4  5  6  4]
 [10 11 12  4]]


In [19]:
arr4.shape

(3, 4)

In [ ]:
arr3.shape

(2, 1, 1, 1, 1, 1, 3)

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
range(10)

range(0, 10)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range(1,10,0.5)

TypeError: ignored

In [ ]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(10,0,-0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

In [22]:

np.array([1.0,2.0,3.0,4.0,True])

array([1., 2., 3., 4., 1.])

In [50]:
np.array([1,2,3,4,8.6,"AKASH"])

array(['1', '2', '3', '4', '8.6', 'AKASH'], dtype='<U32')

In [21]:
np.array([1,2,3],dtype='float')

array([1., 2., 3.])

In [22]:
a = np.array((1,2,3,4,8.6))

In [23]:
a.dtype

dtype('float64')

In [54]:
a

array([1. , 2. , 3. , 4. , 8.6])

In [56]:
a = [234,234,235,2346,523,523,523,5]
np.array(a)[3:5]

array([2346,  523])

In [24]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
# task
1 - import numpy as np
2 - a = np.array([1,2,3])      # create numpy array using list
3 - a+2                        #add 2 to every element
4 - a2 = np.array([1,2],[3,4]) #creat 2d array
5 - a.shape,a.ndim             #use numpy function
6 - np.arange(1,10,0.2)        #use arange
7 - np.array([1,2,3],dtype='float')
8 - np.array([2,234,234,234])[3:5]# slicing on np array

In [58]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [59]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
  if i<6:
    print(i)

1
2
3
4
5


In [61]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [62]:
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [63]:
m1[2]

3

In [65]:
m1[[2,5]]# multiple indesx in list

array([3, 6])

In [66]:
m2 = np.array([1,2,3])

In [67]:
m2

array([1, 2, 3])

In [68]:
m2[[True,False,True]]

array([1, 3])

In [70]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sudher = m1<6

In [71]:
sudher

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [72]:
m1[sudher]

array([1, 2, 3, 4, 5])

In [73]:
# Filtering

In [74]:
m1 = np.arange(1,20)
filter = m1%2==0 #true and false #step1
m1[filter] #step2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

**NPS Problem**

In [77]:
score = np.loadtxt('survey.txt',dtype='int')

In [78]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [79]:
type(score)

numpy.ndarray

In [80]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [82]:
score.shape

(1167,)

In [83]:
len(score)

1167

In [85]:
score.min()

1

In [86]:
score.max()

10

In [ ]:
#there is no record for 0 score

In [87]:
detractors = score[score<=6]
len(detractors)

332

In [90]:
detractors.shape[0]

332

In [91]:
promoters = score[score>=9]
len(promoters)

609

In [93]:
total = len(score)

In [94]:
perc_dect =  (len(detractors)/total)*100
perc_prom =  (len(promoters)/total)*100

In [95]:
perc_prom

52.185089974293064

In [96]:
perc_dect

28.449014567266495

In [97]:
perc_prom - perc_dect

23.73607540702657

In [98]:
score[(score>=5) & (score<8)]

array([7, 5, 7, 7, 5, 7, 5, 5, 5, 5, 7, 7, 5, 5, 7, 5, 7, 5, 7, 7, 7, 7,
       7, 7, 7, 5, 5, 7, 5, 7, 7, 7, 5, 7, 5, 7, 7, 7, 5, 7, 5, 5, 5, 5,
       5, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 7, 5, 5, 7, 7, 5, 7, 7, 5, 7, 7,
       5, 7, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 7, 7, 7, 7, 7, 5, 5, 7, 7,
       7, 7, 5, 5, 5, 5, 5, 5, 7, 5, 7, 7, 5, 5, 5, 7, 7, 7, 7, 7, 5, 7,
       7, 5, 5, 5, 7, 7, 5, 5, 5, 7, 5, 5, 7, 5, 5, 5, 7, 5, 5, 7, 7, 7,
       7, 7, 5, 5, 7, 7, 7, 5, 5, 5, 7, 5, 5, 5, 7, 5, 7, 5, 5, 7, 7, 7,
       5, 7, 7, 7, 7, 7, 7, 5, 5, 7, 7, 5, 5, 7, 7, 5, 7, 5, 7, 5, 7, 5,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 7, 7, 5, 7, 5, 5, 7, 7, 5, 7,
       7, 7, 5, 7, 5, 5, 7, 7, 7, 7, 5, 7, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5,
       7, 7, 7, 7, 7, 5])

In [99]:
a = np.array([1,2,3])


In [111]:
id(a[0])

140677727423856

In [112]:
id(a[1])

140677727431824

In [113]:
id(a[2])

140677727424848

In [116]:
140677727431824-140677727423856

7968

In [117]:
140677727424848-140677727431824

-6976

In [119]:
l= [1,23]
l+[2]

[1, 23, 2]

In [120]:
np.array([1,23])+2

array([ 3, 25])

In [121]:
np.arange(0,2,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [122]:
arr4 = np.arange(0,2,0.2)
list(arr4)

[0.0,
 0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2000000000000002,
 1.4000000000000001,
 1.6,
 1.8]

In [123]:
arr4

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [ ]:
When we use NumPy, the way through which it is made faster through a normal list is because of vectorisation right?